title: Sara Moazez Gharebagh # your name (or website title) here
logo: "/images/git.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Student at Royal Institute of Technology in Stockholm.
  <br><br>
  Familiar with Java, C and Elixir. 
  <br><br>
  <a href="https://www.linkedin.com/in/sara-moazez-gharebagh-b807091a4">View My LinkedIn Profile</a> 


#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
